<h2>Uploaded files:</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <td>id</td>
        <td>name</td>
        <td>link</td>
        <td>downloads</td>
        <td>password-protected?</td>
        <td>created at</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($files as $file): ?>
        <tr>
            <td><?php echo $this->escapeHtml($file->id); ?></td>
            <td><?php echo $this->escapeHtml($file->name); ?></td>
            <td>
                <a href="http://<?php echo gethostname() . '/g/' . $file->link; ?>">http://<?php echo gethostname() . '/g/' . $file->link; ?></a>
            </td>
            <td><?php echo $this->escapeHtml($file->downloads); ?></td>
            <td><?php echo $file->hasPassword() ? 'yes' : 'no'; ?></td>
            <td><?php echo $file->createdAt->format('d.m.Y H:i:s'); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
