<div class="jumbotron">
    <h1>Welcome to FileShare</h1>
    <p>Upload your file now!</p>
</div>
<form action="/application/file/add" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="upload">Select file:</label>
        <input type="file" id="upload" name="upload" class="form-control">
    </div>
    <div class="form-group">
        <label for="passwd">Protect with password (optional):</label>
        <input type="password" id="passwd" name="passwd" class="form-control" placeholder="Password">
    </div>
    <input type="submit" class="btn btn-primary">
</form>
